### ISSUE TITLE
MD HYPE HYPE HYPE

### ISSUE THREAD

**Issue by algmwc5** [algmwc5/sandbox#1]
# Aww dang: the story
## Wat happened?
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
## So, when did you lorem?
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

**Too bald to be bold? never**

_They say that Italic is invented in Italy_

> QUOTE QUOTE QUOTE HYPE
> I'm not joking

`CODE HYPE`

[link to somewhere...](drkat.gwiddle.co.uk)

- LIST LIST LIST
- LOST IN THE MIDDLE
- LAST PLACE GETS NOTHING

**Comment by DrKat123** [comment]
1. Numero uno
2. counting HYPE
3. FIBONACCI MADNESS

- [x] Check please

#lolewat

**Comment by DrKat123** [comment]
![IMAGE OF A VIOLA DA AMORE HYPE](https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/Viola_d%27amore.jpg/250px-Viola_d%27amore.jpg)

**Comment by DrKat123** [comment]
- [X] ![HYPE](https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Viola_d%27amore_1.jpg/250px-Viola_d%27amore_1.jpg)

**Comment by DrKat123** [comment]
> ![HYPE.exe](https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/Heinrich_Biber.png/250px-Heinrich_Biber.png)

**Comment by DrKat123** [comment]
```C
#include <includer.c>;
#define forevr for(;;)
main(){
    include("php.c");
    thang(){
        include("c-parser-for-c.c");
    }
}```

**Comment by DrKat123** [comment]
#### Wat
# Wat
### WAT

**Comment by DrKat123** [comment]
# Waat
Lorem ist wat in the haus 
Lorem, wat ist es?
## Code thing
```JS
include("codeblocks.js");
codeblock_1(var x = 10){
    console.log(x*2);
}
```
### How to hype
Hype hype [hype](http://example.com) hype hype hype hype the code

**Comment by DrKat123** [comment]
# _Italic Heads_

**Comment by liam4** [comment]
FYI there's a previewer :P
![](https://cloud.githubusercontent.com/assets/9948030/14370174/baa3dbb2-fd01-11e5-8f9a-655a50e7c8fc.png)

**Comment by DrKat123** [comment]
~~i dunno~~ i kno alright

MD _***HYPE HYPE HYPE MANIA***_

**Comment by DrKat123** [comment]
>umm
> >wat
> > > is going
> > > >on

**Comment by DrKat123** [comment]
> > > > hyper quote chain

**Comment by DrKat123** [comment]
Lelwat

# ~~This iz quotz~~

**Comment by DrKat123** [comment]
# ~~***_help_***~~
