### ISSUE TITLE
MENTION MANIA

### ISSUE THREAD

**Issue by algmwc5** [algmwc5/sandbox#4]
@scratchyone 
@jupiterio
@mrcomputer1
@tymewalk
@dylan5797

**Comment by DrKat123** [comment]
:smiling_imp:

**Comment by Mrcomputer1** [comment]
:stuck_out_tongue:

**Comment by Tymewalk** [comment]
:open_mouth: Is this my invitation to become a wizard?

**Comment by liam4** [comment]
![](http://data.whicdn.com/images/12190379/large.png)

**Comment by Dylan5797** [comment]
wow thx for the email flood

**Comment by Dylan5797** [comment]
Is there any particular reason you mentioned me?

**Comment by Tymewalk** [comment]
@liam4 YES I KNEW IT! XD

**Comment by Dylan5797** [comment]
lol

**Comment by Tymewalk** [comment]
So... what now?

**Comment by DrKat123** [comment]
This is a sannbox m8

My sandbox

:stuck_out_tongue:


Mention mania

@TheInitializer
@colt05

Aaaand i'm too lazy to mention others

**Comment by DrKat123** [comment]
Now how to close this issue on ForkHub...

**Comment by DrKat123** [comment]
Found it

**Comment by TheInitializer** [comment]
why

**Comment by DrKat123** [comment]
This is a sandbox :P

**Comment by TheInitializer** [comment]
ok muting

**Comment by DrKat123** [comment]
Dude
This is already closed

**Comment by DrKat123** [comment]
Hey everybody look
I h4ck3d some users

**Comment by DrKat123** [comment]
@scratchyone 
@jupiterio
@mrcomputer1
@tymewalk
@dylan5797
Plz come

**Comment by DrKat123** [comment]
Lelh4x0r$r4z0r$

**Comment by colt05** [comment]
hi

**Comment by DrKat123** [comment]
Hi

**Comment by DrKat123** [comment]
@colt05 i just h4x3d you good

**Comment by DrKat123** [comment]
:shipit:

**Comment by Tymewalk** [comment]
Wait... how did you do that?

**Comment by Dylan5797** [comment]
Owners of issues can edit any comments they want

**Comment by DrKat123** [comment]
:smiling_imp:

**Comment by jupiterio** [comment]
hAAAAAAAAAAAAAAi
ohaio~~!!!
watashi wa io desu!!

**Comment by jupiterio** [comment]
sugoi~~~~!!!!!!!!

**Comment by DrKat123** [comment]
HAXMANIA

**Comment by jupiterio** [comment]
Asombroso! Espléndido! Esto es una maravilla del mundo! Me han hackeado! :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit:

**Comment by DrKat123** [comment]
more hacking means more fun

**Comment by liam4** [comment]
*unsubscribed*

**Comment by colt05** [comment]
AAAAAAGHHHHHHHHHHHHH

**Comment by colt05** [comment]
how did u do that??

**Comment by colt05** [comment]
oh I think I know....
